### ISSUE TITLE
JS files are symlinks

### ISSUE THREAD

**Issue by anoadragon453** [LetsTox/stats#1]
Not actually in the repo. Not sure if this is intentional.

**Comment by GrayHatter** [comment]
@anoadragon453 they're links to a git repo elsewhere on the server. 

All of the files are just amchart files https://github.com/amcharts/amcharts3

You can reopen this if you think it needs to include the actual files.

**Comment by anoadragon453** [comment]
Perhaps they don't have to be included, but alerting developers amcharts3 is a dependency might be a good idea (in a readme or similar).
